# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 George Saliba
"""Build script: concatenates all .pas files into a single Altium_MCP.pas"""
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Files in correct declaration order
FILES = [
    'Main.pas',
    'Utils.pas',
    'Application.pas',
    'Project.pas',
    'Library.pas',
    'PCBGeneric.pas',
    'PCB.pas',
    'Generic.pas',
    'Dispatcher.pas',
]

OUTPUT = os.path.join(SCRIPT_DIR, 'Altium_MCP.pas')

header = """{ SPDX-License-Identifier: Apache-2.0                                   }
{ Copyright (c) 2026 George Saliba                                      }
{..............................................................................}
{ Altium_MCP.pas - Monolithic build of all Altium integration bridge               }
{ AUTO-GENERATED by build.py - Do not edit directly.                         }
{ Edit the individual .pas source files and re-run build.py instead.         }
{..............................................................................}

"""

with open(OUTPUT, 'w', encoding='utf-8') as out:
    out.write(header)
    for fname in FILES:
        path = os.path.join(SCRIPT_DIR, fname)
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        out.write(f'{{=== {fname} ===}}\n')
        out.write(content)
        if not content.endswith('\n'):
            out.write('\n')
        out.write('\n')

print(f'Built {OUTPUT}')
print(f'Total files: {len(FILES)}')
size = os.path.getsize(OUTPUT)
print(f'Output size: {size} bytes')
