{ SPDX-License-Identifier: Apache-2.0                                   }
{ Copyright (c) 2026 George Saliba                                      }
{
  Cross-validation Pascal program.

  Reads test cases from cross_validate_inputs.txt (generated by Python),
  runs each through the REAL Pascal function (copied from Main.pas / Utils.pas),
  writes results to cross_validate_outputs.txt.

  The Python test then compares Pascal outputs against Python reimplementation
  outputs to prove they are identical.

  Protocol:
    Input:  FUNCTION_NAME<TAB>base64(arg1)<TAB>base64(arg2)<TAB>...
    Output: base64(result)   (one per line, matching input order)

  Compile (adjust -Fu to point at your FPC fcl-base unit path; on many
  installs fpc.cfg already has this and plain `fpc` works):
    fpc -Fu<path-to-fpc>/units/i386-win32/fcl-base cross_validate_pascal.pas
  Run:
    cross_validate_pascal.exe <input_file> <output_file>
}
program cross_validate_pascal;

{$mode delphi}

uses
  SysUtils, Classes, base64;

{ ========================================================================= }
{ Functions under test - EXACT copies from Main.pas and Utils.pas            }
{ ========================================================================= }

{ --- From Utils.pas --- }

function MilsToCoord(Mils : Integer) : Integer;
begin
  Result := Mils * 10000;
end;

function CoordToMils(Coord : Integer) : Integer;
begin
  Result := Round(Coord / 10000);
end;

function MMToCoord(MM : Double) : Integer;
begin
  Result := Round(MM * 10000000 / 25.4);
end;

function CoordToMM(Coord : Integer) : Double;
begin
  Result := Coord * 25.4 / 10000000;
end;

function BoolToJsonStr(Value : Boolean) : String;
begin
  if Value then Result := 'true'
  else Result := 'false';
end;

function StrToBoolCustom(S : String) : Boolean;
begin
  Result := (LowerCase(S) = 'true') or (S = '1');
end;

function StrToIntDefCustom(S : String; Default : Integer) : Integer;
begin
  if (S = '') or (S = 'null') then
    Result := Default
  else
  begin
    try
      Result := StrToInt(S);
    except
      Result := Default;
    end;
  end;
end;

function StrToFloatDefCustom(S : String; Default : Double) : Double;
begin
  if (S = '') or (S = 'null') then
    Result := Default
  else
  begin
    try
      Result := StrToFloat(S);
    except
      Result := Default;
    end;
  end;
end;

function EscapeJsonString(S : String) : String;
begin
  Result := S;
  Result := StringReplace(Result, '\', '\\', [rfReplaceAll]);
  Result := StringReplace(Result, '"', '\"', [rfReplaceAll]);
  Result := StringReplace(Result, #13, '\r', [rfReplaceAll]);
  Result := StringReplace(Result, #10, '\n', [rfReplaceAll]);
  Result := StringReplace(Result, #9, '\t', [rfReplaceAll]);
end;

{ --- Property store: "Name=Value|Name=Value|..." --- }
{ Used as a stand-in for ISch_GraphicalObject property access.            }
{ Encodes the parsing/construction logic of MatchesFilter/BuildObjectJson  }
{ /ApplySetProperties WITHOUT depending on Altium API types.              }

function GetStoredProperty(PropStore : String; Name : String) : String;
var
  Remaining, Entry, EntryName, EntryValue : String;
  PipePos, EqPos : Integer;
begin
  Result := '';
  Remaining := PropStore;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Entry := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Entry := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Entry);
    if EqPos = 0 then Continue;
    EntryName := Copy(Entry, 1, EqPos - 1);
    EntryValue := Copy(Entry, EqPos + 1, Length(Entry));

    if EntryName = Name then
    begin
      Result := EntryValue;
      Exit;
    end;
  end;
end;

function SetStoredProperty(PropStore : String; Name : String; Value : String) : String;
var
  Remaining, Entry, EntryName : String;
  PipePos, EqPos : Integer;
  Found : Boolean;
begin
  Result := '';
  Remaining := PropStore;
  Found := False;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Entry := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Entry := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Entry);
    if EqPos > 0 then
    begin
      EntryName := Copy(Entry, 1, EqPos - 1);
      if EntryName = Name then
      begin
        Entry := Name + '=' + Value;
        Found := True;
      end;
    end;

    if Result <> '' then Result := Result + '|';
    Result := Result + Entry;
  end;
  if not Found then
  begin
    if Result <> '' then Result := Result + '|';
    Result := Result + Name + '=' + Value;
  end;
end;

{ --- MatchesFilter (from Generic.pas) --- }
{ Port of the pipe-separated filter parsing:                               }
{   "PropName=Value|PropName=Value" (AND logic).                          }
{ Returns 'true'/'false'.                                                  }

function MatchesFilter(PropStore : String; FilterStr : String) : String;
var
  Remaining, Condition, PropName, Expected, Actual : String;
  PipePos, EqPos : Integer;
begin
  Result := 'true';
  if FilterStr = '' then Exit;

  Remaining := FilterStr;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Condition := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Condition := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Condition);
    if EqPos = 0 then Continue;
    PropName := Copy(Condition, 1, EqPos - 1);
    Expected := Copy(Condition, EqPos + 1, Length(Condition));

    Actual := GetStoredProperty(PropStore, PropName);
    if Actual <> Expected then
    begin
      Result := 'false';
      Exit;
    end;
  end;
end;

{ --- BuildObjectJson (from Generic.pas) --- }
{ Port of comma-separated property list -> JSON object with escaped vals. }

function BuildObjectJson(PropStore : String; PropsStr : String) : String;
var
  Remaining, PropName, PropValue : String;
  CommaPos : Integer;
  First : Boolean;
begin
  Result := '{';
  First := True;
  Remaining := PropsStr;

  while Remaining <> '' do
  begin
    CommaPos := Pos(',', Remaining);
    if CommaPos > 0 then
    begin
      PropName := Copy(Remaining, 1, CommaPos - 1);
      Remaining := Copy(Remaining, CommaPos + 1, Length(Remaining));
    end
    else
    begin
      PropName := Remaining;
      Remaining := '';
    end;

    PropValue := GetStoredProperty(PropStore, PropName);

    if not First then Result := Result + ',';
    First := False;
    Result := Result + '"' + EscapeJsonString(PropName) + '":"' + EscapeJsonString(PropValue) + '"';
  end;

  Result := Result + '}';
end;

{ --- ApplySetProperties (from Generic.pas) --- }
{ Port of pipe-separated "PropName=Value" assignments. Returns modified    }
{ property store.                                                          }

function ApplySetProperties(PropStore : String; SetStr : String) : String;
var
  Remaining, Assignment, PropName, PropValue : String;
  PipePos, EqPos : Integer;
begin
  Result := PropStore;
  Remaining := SetStr;
  while Remaining <> '' do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos > 0 then
    begin
      Assignment := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end
    else
    begin
      Assignment := Remaining;
      Remaining := '';
    end;

    EqPos := Pos('=', Assignment);
    if EqPos = 0 then Continue;
    PropName := Copy(Assignment, 1, EqPos - 1);
    PropValue := Copy(Assignment, EqPos + 1, Length(Assignment));

    Result := SetStoredProperty(Result, PropName, PropValue);
  end;
end;

{ --- BatchModify operation splitting (from Gen_BatchModify) --- }
{ Parses pipe-separated operations, each "scope;object_type;filter;set",  }
{ and returns the count of VALID operations (object_type != '' and        }
{ set != ''). Mirrors the iteration/counting portion of Gen_BatchModify.  }

function CountBatchOperations(Operations : String) : Integer;
var
  Remaining, OpStr, Scope, ObjTypeStr, FilterStr, SetStr : String;
  PipePos, SemiPos : Integer;
  OpCount : Integer;
begin
  OpCount := 0;
  Remaining := Operations;

  while Length(Remaining) > 0 do
  begin
    PipePos := Pos('|', Remaining);
    if PipePos = 0 then
    begin
      OpStr := Remaining;
      Remaining := '';
    end
    else
    begin
      OpStr := Copy(Remaining, 1, PipePos - 1);
      Remaining := Copy(Remaining, PipePos + 1, Length(Remaining));
    end;

    if OpStr = '' then Continue;

    SemiPos := Pos(';', OpStr);
    if SemiPos = 0 then Continue;
    Scope := Copy(OpStr, 1, SemiPos - 1);
    OpStr := Copy(OpStr, SemiPos + 1, Length(OpStr));

    SemiPos := Pos(';', OpStr);
    if SemiPos = 0 then Continue;
    ObjTypeStr := Copy(OpStr, 1, SemiPos - 1);
    OpStr := Copy(OpStr, SemiPos + 1, Length(OpStr));

    SemiPos := Pos(';', OpStr);
    if SemiPos = 0 then Continue;
    FilterStr := Copy(OpStr, 1, SemiPos - 1);
    SetStr := Copy(OpStr, SemiPos + 1, Length(OpStr));

    if (ObjTypeStr = '') or (SetStr = '') then Continue;

    { Silence "assigned but not used" -- these are structural checks }
    if Scope = #0 then Exit;
    if FilterStr = #0 then Exit;

    Inc(OpCount);
  end;

  Result := OpCount;
end;

{ --- Command routing split on '.' (from Dispatcher.pas) --- }
{ Returns "Category|Action" string. Action is empty if no dot.             }

function SplitCommand(Command : String) : String;
var
  Category, Action : String;
  DotPos : Integer;
begin
  DotPos := Pos('.', Command);
  if DotPos > 0 then
  begin
    Category := Copy(Command, 1, DotPos - 1);
    Action := Copy(Command, DotPos + 1, Length(Command));
  end
  else
  begin
    Category := Command;
    Action := '';
  end;
  Result := Category + '|' + Action;
end;

{ --- From Main.pas --- }

function IsWhitespaceOrColon(S : String; Idx : Integer) : Boolean;
var
  C : String;
begin
  C := Copy(S, Idx, 1);
  Result := (C = ' ') or (C = ':') or (C = #9) or (C = #10) or (C = #13);
end;

function IsDelimiter(S : String; Idx : Integer) : Boolean;
var
  C : String;
begin
  C := Copy(S, Idx, 1);
  Result := (C = '') or (C = ',') or (C = '}') or (C = ']') or (C = ' ') or (C = #9) or (C = #10) or (C = #13);
end;

{ This is the REAL ExtractJsonValue from Main.pas with proper backslash counting }
function ExtractJsonValue(Json : String; Key : String) : String;
var
  StartPos, EndPos : Integer;
  SearchKey : String;
  BraceCount : Integer;
  BackslashCount, TempPos : Integer;
begin
  Result := '';
  SearchKey := '"' + Key + '"';
  StartPos := Pos(SearchKey, Json);
  if StartPos > 0 then
  begin
    StartPos := StartPos + Length(SearchKey);
    while (StartPos <= Length(Json)) and IsWhitespaceOrColon(Json, StartPos) do
      Inc(StartPos);

    if StartPos <= Length(Json) then
    begin
      if Copy(Json, StartPos, 1) = '"' then
      begin
        Inc(StartPos);
        EndPos := StartPos;
        while (EndPos <= Length(Json)) do
        begin
          if Copy(Json, EndPos, 1) = '"' then
          begin
            BackslashCount := 0;
            TempPos := EndPos - 1;
            while (TempPos >= StartPos) and (Copy(Json, TempPos, 1) = '\') do
            begin
              Inc(BackslashCount);
              Dec(TempPos);
            end;
            if (BackslashCount mod 2) = 0 then Break;
          end;
          Inc(EndPos);
        end;
        Result := Copy(Json, StartPos, EndPos - StartPos);
      end
      else if Copy(Json, StartPos, 1) = '{' then
      begin
        EndPos := StartPos;
        BraceCount := 1;
        Inc(EndPos);
        while (EndPos <= Length(Json)) and (BraceCount > 0) do
        begin
          if Copy(Json, EndPos, 1) = '{' then Inc(BraceCount)
          else if Copy(Json, EndPos, 1) = '}' then Dec(BraceCount);
          Inc(EndPos);
        end;
        Result := Copy(Json, StartPos, EndPos - StartPos);
      end
      else
      begin
        EndPos := StartPos;
        while (EndPos <= Length(Json)) and (not IsDelimiter(Json, EndPos)) do
          Inc(EndPos);
        Result := Copy(Json, StartPos, EndPos - StartPos);
      end;
    end;
  end;
end;

function ExtractJsonArray(Json : String; Key : String) : String;
var
  StartPos, EndPos : Integer;
  SearchKey : String;
  BracketCount : Integer;
begin
  Result := '';
  SearchKey := '"' + Key + '"';
  StartPos := Pos(SearchKey, Json);
  if StartPos > 0 then
  begin
    StartPos := StartPos + Length(SearchKey);
    while (StartPos <= Length(Json)) and IsWhitespaceOrColon(Json, StartPos) do
      Inc(StartPos);

    if (StartPos <= Length(Json)) and (Copy(Json, StartPos, 1) = '[') then
    begin
      EndPos := StartPos;
      BracketCount := 1;
      Inc(EndPos);
      while (EndPos <= Length(Json)) and (BracketCount > 0) do
      begin
        if Copy(Json, EndPos, 1) = '[' then Inc(BracketCount)
        else if Copy(Json, EndPos, 1) = ']' then Dec(BracketCount);
        Inc(EndPos);
      end;
      Result := Copy(Json, StartPos, EndPos - StartPos);
    end;
  end;
end;

function BuildSuccessResponse(RequestId : String; Data : String) : String;
begin
  if Data = '' then
    Data := 'null';
  Result := '{"id":"' + RequestId + '","success":true,"data":' + Data + ',"error":null}';
end;

function BuildErrorResponse(RequestId : String; ErrorCode : String; ErrorMsg : String) : String;
begin
  ErrorMsg := StringReplace(ErrorMsg, '\', '\\', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, '"', '\"', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, #13, '\r', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, #10, '\n', [rfReplaceAll]);
  ErrorMsg := StringReplace(ErrorMsg, #9, '\t', [rfReplaceAll]);
  Result := '{"id":"' + RequestId + '","success":false,"data":null,"error":{"code":"' + ErrorCode + '","message":"' + ErrorMsg + '"}}';
end;

{ ========================================================================= }
{ Dispatcher                                                                 }
{ ========================================================================= }

function B64Decode(S : String) : String;
begin
  { Convention: '_' means empty string (avoids empty base64 fields) }
  if (S = '') or (S = '_') then
    Result := ''
  else
    Result := DecodeStringBase64(S);
end;

function B64Encode(S : String) : String;
begin
  { Convention: '_' means empty string (avoids empty base64 output lines) }
  if S = '' then
    Result := '_'
  else
    Result := EncodeStringBase64(S);
end;

procedure ProcessLine(Line : String; var OutFile : TextFile);
var
  Parts : TStringList;
  FnName : String;
  ResultStr : String;
  IntResult : Integer;
  FloatResult : Double;
  BoolResult : Boolean;
begin
  Parts := TStringList.Create;
  try
    Parts.Delimiter := #9;
    Parts.StrictDelimiter := True;
    Parts.DelimitedText := Line;

    if Parts.Count < 1 then Exit;
    FnName := Parts[0];
    ResultStr := '';

    { --- ExtractJsonValue: args = json_str, key --- }
    if FnName = 'ExtractJsonValue' then
    begin
      ResultStr := ExtractJsonValue(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- ExtractJsonArray: args = json_str, key --- }
    else if FnName = 'ExtractJsonArray' then
    begin
      ResultStr := ExtractJsonArray(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- EscapeJsonString: args = s --- }
    else if FnName = 'EscapeJsonString' then
    begin
      ResultStr := EscapeJsonString(B64Decode(Parts[1]));
    end

    { --- BuildSuccessResponse: args = request_id, data --- }
    else if FnName = 'BuildSuccessResponse' then
    begin
      ResultStr := BuildSuccessResponse(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- BuildErrorResponse: args = request_id, error_code, error_msg --- }
    else if FnName = 'BuildErrorResponse' then
    begin
      ResultStr := BuildErrorResponse(B64Decode(Parts[1]), B64Decode(Parts[2]), B64Decode(Parts[3]));
    end

    { --- MilsToCoord: args = mils (int) --- }
    else if FnName = 'MilsToCoord' then
    begin
      IntResult := MilsToCoord(StrToInt(B64Decode(Parts[1])));
      ResultStr := IntToStr(IntResult);
    end

    { --- CoordToMils: args = coord (int) --- }
    else if FnName = 'CoordToMils' then
    begin
      IntResult := CoordToMils(StrToInt(B64Decode(Parts[1])));
      ResultStr := IntToStr(IntResult);
    end

    { --- MMToCoord: args = mm (float) --- }
    else if FnName = 'MMToCoord' then
    begin
      FloatResult := StrToFloat(B64Decode(Parts[1]));
      IntResult := MMToCoord(FloatResult);
      ResultStr := IntToStr(IntResult);
    end

    { --- CoordToMM: args = coord (int) --- }
    else if FnName = 'CoordToMM' then
    begin
      FloatResult := CoordToMM(StrToInt(B64Decode(Parts[1])));
      { Use enough decimal places to distinguish, match Python formatting }
      ResultStr := FormatFloat('0.0000000000', FloatResult);
    end

    { --- StrToIntDef: args = s, default (int) --- }
    else if FnName = 'StrToIntDef' then
    begin
      IntResult := StrToIntDefCustom(B64Decode(Parts[1]), StrToInt(B64Decode(Parts[2])));
      ResultStr := IntToStr(IntResult);
    end

    { --- StrToFloatDef: args = s, default (float) --- }
    else if FnName = 'StrToFloatDef' then
    begin
      FloatResult := StrToFloatDefCustom(B64Decode(Parts[1]), StrToFloat(B64Decode(Parts[2])));
      ResultStr := FormatFloat('0.0000000000', FloatResult);
    end

    { --- BoolToJsonStr: args = bool_str ("true"/"false") --- }
    else if FnName = 'BoolToJsonStr' then
    begin
      BoolResult := (LowerCase(B64Decode(Parts[1])) = 'true');
      ResultStr := BoolToJsonStr(BoolResult);
    end

    { --- StrToBool: args = s --- }
    else if FnName = 'StrToBool' then
    begin
      BoolResult := StrToBoolCustom(B64Decode(Parts[1]));
      if BoolResult then
        ResultStr := 'true'
      else
        ResultStr := 'false';
    end

    { --- MatchesFilter: args = prop_store, filter_str --- }
    else if FnName = 'MatchesFilter' then
    begin
      ResultStr := MatchesFilter(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- BuildObjectJson: args = prop_store, props_str --- }
    else if FnName = 'BuildObjectJson' then
    begin
      ResultStr := BuildObjectJson(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- ApplySetProperties: args = prop_store, set_str --- }
    else if FnName = 'ApplySetProperties' then
    begin
      ResultStr := ApplySetProperties(B64Decode(Parts[1]), B64Decode(Parts[2]));
    end

    { --- CountBatchOperations: args = operations_str --- }
    else if FnName = 'CountBatchOperations' then
    begin
      IntResult := CountBatchOperations(B64Decode(Parts[1]));
      ResultStr := IntToStr(IntResult);
    end

    { --- SplitCommand: args = command_str --- }
    else if FnName = 'SplitCommand' then
    begin
      ResultStr := SplitCommand(B64Decode(Parts[1]));
    end

    else
    begin
      ResultStr := 'ERROR:UNKNOWN_FUNCTION:' + FnName;
    end;

    WriteLn(OutFile, B64Encode(ResultStr));
  finally
    Parts.Free;
  end;
end;

{ ========================================================================= }
{ Main                                                                       }
{ ========================================================================= }

var
  InputPath, OutputPath : String;
  InFile, OutFile : TextFile;
  Line : String;
  LineCount : Integer;

begin
  { Set decimal separator to '.' for consistent float formatting }
  {$IFDEF FPC}
  DefaultFormatSettings.DecimalSeparator := '.';
  {$ENDIF}

  if ParamCount < 2 then
  begin
    WriteLn('Usage: cross_validate_pascal.exe <input_file> <output_file>');
    Halt(1);
  end;

  InputPath := ParamStr(1);
  OutputPath := ParamStr(2);

  if not FileExists(InputPath) then
  begin
    WriteLn('Error: input file not found: ', InputPath);
    Halt(1);
  end;

  AssignFile(InFile, InputPath);
  Reset(InFile);

  AssignFile(OutFile, OutputPath);
  Rewrite(OutFile);

  LineCount := 0;
  try
    while not EOF(InFile) do
    begin
      ReadLn(InFile, Line);
      if Length(Line) > 0 then
      begin
        ProcessLine(Line, OutFile);
        Inc(LineCount);
      end;
    end;
  finally
    CloseFile(InFile);
    CloseFile(OutFile);
  end;

  WriteLn('Processed ', LineCount, ' test cases.');
end.
